import type { ChoiceBankItem } from "../../../bankGenre";

// "Fill the Gap" (cousin of word knowledge, VC domain), reauthored
// 2026-08-30 under decision #29 after an audit found the whole bank was
// solvable by register alone ("pick the rarer word" scored 2 on about 48 of
// 50 items) with a recycled pool of never the answer fillers.
//
// Design rules this bank now follows:
//  1. The SENTENCE carries the evidence. Every stem contains the detail that
//     picks the 2 point word over the 1 point near synonym (a whole night of
//     rain picks soaked over damp; two tall trees pick ambiguous over
//     unclear). Nothing depends on knowing which word sounds fancier.
//  2. Four options of one kind: same part of speech, same word form (all the
//     picture items are ing verbs), same register and frequency band, similar
//     length. No option can be dropped on tone, grammar, article or length.
//  3. The 1 point option is genuinely partial: right direction, less precise
//     or less complete for THIS sentence. The two 0 point options are real
//     words a child could reasonably try, true of a similar sentence, never
//     silly, never cruel, never a color.
//  4. 50 distinct keys, and no key is used as a distractor anywhere. No
//     filler word sits in more than two items. No intensifier before the
//     blank, no article before the blank, and the key never echoes the stem.
//  5. Difficulty comes from the precision demanded, not from rarer words.
//     d1 to d2 concrete actions with in sentence evidence (emoji present, and
//     the emoji shows the scene or the subject, never the answer); d3 to d4 everyday
//     adjectives; d5 to d6 feelings and qualities in subtle shades; d7 to d8
//     academic adjectives; d9 to d10 abstract nouns and precise academic
//     vocabulary. d1 is about age 6, d10 about age 13.
//  6. Every item carries a reviewNote recording the human red team pass.
export const FILL_THE_GAP_BANK: ChoiceBankItem[] = [
  // d1: picture items, about age 6. All four options are ing verbs the animal
  // or object could really do; the sentence says which one.
  {
    id: "fg-01", d: 1, prompt: "The cat is ___ on the mat and has not opened her eyes since lunch.", emoji: "🐱",
    options: [
      { text: "sleeping", points: 2 },
      { text: "resting", points: 1 },
      { text: "hunting", points: 0 },
      { text: "prowling", points: 0 },
    ],
    explanation: "Eyes that have stayed shut since lunch mean the cat is sleeping, not only resting.",
    definition: "Resting with your eyes closed, not awake at all.",
    example: "My little brother is sleeping in his cozy bed.",
    reviewNote: "Hunting and prowling are true cat verbs but both mean moving after something, which no cat lying still on a mat is doing. Resting is the right direction and earns partial credit, yet a cat can rest wide awake with her eyes following you round the room. Has not opened her eyes since lunch is the evidence in the sentence itself, so sleeping is uniquely right. Seven and eight letters, all ing forms, all plain register, the cat emoji shows the animal and not the action, and no option is silly.",
  },
  {
    id: "fg-02", d: 1, prompt: "The frog is ___ from one lily pad to the next.", emoji: "🐸",
    options: [
      { text: "hopping", points: 2 },
      { text: "moving", points: 1 },
      { text: "floating", points: 0 },
      { text: "diving", points: 0 },
    ],
    explanation: "Going from pad to pad in little jumps is hopping.",
    definition: "Moving along by making lots of small jumps.",
    example: "The bunny is hopping across the garden.",
    reviewNote: "Floating and diving are things that really happen on a pond, but neither gets you from one pad to another pad. Moving is true and scores one, yet it names no way of travelling. From one lily pad to the next is the evidence: crossing a gap needs a jump, so hopping is uniquely right. All four are ing verbs of six to eight letters in the same plain register, the frog emoji shows the subject not the answer, the key never appears in the stem, and nothing here is silly or moralized.",
  },
  {
    id: "fg-03", d: 1, prompt: "The baby is ___ across the floor on her hands and knees.", emoji: "👶",
    options: [
      { text: "crawling", points: 2 },
      { text: "creeping", points: 1 },
      { text: "rolling", points: 0 },
      { text: "stomping", points: 0 },
    ],
    explanation: "Moving on hands and knees is what crawling means.",
    definition: "Moving on your hands and knees, close to the floor.",
    example: "The bug is crawling up the wall.",
    reviewNote: "Rolling and stomping are real ways of crossing a floor and both fit a slightly different sentence, but neither uses hands and knees. Creeping is close and earns one, yet it only says slow and quiet and could be done on tiptoe. On her hands and knees is the clause that makes crawling the exact fit. Lengths run seven to eight letters, all ing forms, all everyday words, the baby emoji shows the subject, and no distractor is babyish or absurd.",
  },
  {
    id: "fg-04", d: 1, prompt: "The bus is ___ at the corner so the children can climb on.", emoji: "🚌",
    options: [
      { text: "stopping", points: 2 },
      { text: "slowing", points: 1 },
      { text: "swerving", points: 0 },
      { text: "turning", points: 0 },
    ],
    explanation: "Children can only climb on once the bus has come to a full halt, so it is stopping.",
    definition: "Coming to a still place and not moving anymore.",
    example: "The train is stopping at the station.",
    reviewNote: "Swerving and turning are true bus verbs at a corner and are plausible in a similar sentence, but neither lets anyone climb aboard. Slowing points the right way and takes one, yet a bus that is only slowing is still moving. So the children can climb on is the evidence that demands a full halt. Four ing verbs of seven and eight letters, same register, bus emoji shows the vehicle rather than the action, key absent from the stem, no silliness.",
  },
  {
    id: "fg-05", d: 1, prompt: "The ice cube is ___ fast because Aoife is holding it in her warm hand.", emoji: "🧊",
    options: [
      { text: "melting", points: 2 },
      { text: "shrinking", points: 1 },
      { text: "cracking", points: 0 },
      { text: "spinning", points: 0 },
    ],
    explanation: "A warm hand turns ice into water, and that change is melting.",
    definition: "Turning soft and runny because it is getting warm.",
    example: "My ice cream is melting in the sun.",
    reviewNote: "Cracking and spinning are things ice really does in other sentences, but a warm hand causes neither. Shrinking is the right direction and scores one because the cube truly is getting smaller, yet it says nothing about turning into water. Warm hand is the evidence that names the change, so melting is uniquely right. Seven to nine letters, all ing forms, plain register, the ice emoji shows the object not the change, and no option is a color or a joke.",
  },
  // d2: picture items, about age 6 to 7. Same shape as d1, but the 2 point
  // word is a step more specific than the 1 point one.
  {
    id: "fg-06", d: 2, prompt: "The river is ___ so fast that it carries whole branches away.", emoji: "🏞️",
    options: [
      { text: "rushing", points: 2 },
      { text: "flowing", points: 1 },
      { text: "sinking", points: 0 },
      { text: "spilling", points: 0 },
    ],
    explanation: "Water strong enough to carry branches away is rushing.",
    definition: "Moving very fast, in a big hurry.",
    example: "The children are rushing to the playground.",
    reviewNote: "Sinking and spilling are real water verbs that fit other sentences, but a river that carries branches downstream is doing neither. Flowing is true of every river and takes one, yet it carries no sense of force. Carries whole branches away is the evidence for speed and power, so rushing is uniquely right. All four are ing verbs of seven or eight letters in the same register, the landscape emoji shows the river rather than its speed, and no distractor is silly.",
  },
  {
    id: "fg-07", d: 2, prompt: "The bread is ___ in the oven and filling the house with a warm smell.", emoji: "🍞",
    options: [
      { text: "baking", points: 2 },
      { text: "cooking", points: 1 },
      { text: "chilling", points: 0 },
      { text: "burning", points: 0 },
    ],
    explanation: "Bread in a hot oven is baking, which is the special word for cooking bread.",
    definition: "Cooking something like bread or cake inside a hot oven.",
    example: "Grandma is baking cookies for the party.",
    reviewNote: "Chilling belongs to a fridge and burning would give a sharp smell instead of a warm one, so both are plausible in a neighboring sentence and ruled out here. Cooking is true and scores one, yet it is the general word for any food and any method. Oven plus a warm smell picks the one method bread gets, so baking is uniquely right. Six to eight letters, all ing forms, the loaf emoji shows the bread not the process, and no option is fancier than the rest.",
  },
  {
    id: "fg-08", d: 2, prompt: "The puppy is ___ a hole under the fence to get into the yard.", emoji: "🐶",
    options: [
      { text: "digging", points: 2 },
      { text: "scratching", points: 1 },
      { text: "sniffing", points: 0 },
      { text: "chewing", points: 0 },
    ],
    explanation: "Making a hole in the dirt with his paws is digging.",
    definition: "Making a hole by moving dirt out of the way.",
    example: "We are digging in the sand at the beach.",
    reviewNote: "Sniffing and chewing are ordinary puppy actions that suit a similar sentence, but neither one opens a way under a fence. Scratching is the right direction and takes one because his paws really are scratching, yet scratching alone makes marks rather than a hole. A hole that gets him into the yard is the evidence, so digging is uniquely right. All four are ing verbs, seven to ten letters, same plain register, and the dog emoji shows the puppy rather than the action.",
  },
  {
    id: "fg-09", d: 2, prompt: "The library bell is ___ to tell everyone that story time is starting.", emoji: "📖",
    options: [
      { text: "ringing", points: 2 },
      { text: "sounding", points: 1 },
      { text: "shining", points: 0 },
      { text: "rattling", points: 0 },
    ],
    explanation: "The clear note a bell makes to call people together is ringing.",
    definition: "Making a loud, clear sound, the way a bell does.",
    example: "The phone is ringing in the kitchen.",
    reviewNote: "Shining fits a polished bell and rattling fits one shaken loose on its bracket, so both are believable elsewhere and neither is the clear note a bell is rung for. Sounding is the right direction and scores one, yet it is the general word for making any noise at all. To tell everyone story time is starting is the evidence for a deliberate signal, so ringing is uniquely right. Seven and eight letters, all ing forms, and the open book emoji points at story time rather than at the answer.",
  },
  {
    id: "fg-10", d: 2, prompt: "The rain is ___ against the window so hard that we cannot hear the radio.", emoji: "🌧️",
    options: [
      { text: "pounding", points: 2 },
      { text: "falling", points: 1 },
      { text: "misting", points: 0 },
      { text: "sprinkling", points: 0 },
    ],
    explanation: "Rain loud enough to drown out the radio is pounding on the glass.",
    definition: "Hitting something hard, again and again, with a loud thump.",
    example: "The drummer is pounding on the big drum.",
    reviewNote: "Misting and sprinkling are true rain verbs, which is what makes them tempting, but both describe gentle rain that no one could hear over a radio. Falling is true of all rain and takes one, yet it says nothing about force. So hard that we cannot hear the radio is the evidence, so pounding is uniquely right. Seven to ten letters, all ing forms, same register, and the rain cloud emoji shows the weather rather than how hard it hits.",
  },
  // d3: everyday adjectives, about age 7 to 8. The sentence names the effect;
  // the child picks the adjective that causes exactly that effect.
  {
    id: "fg-11", d: 3, prompt: "The path was so ___ that we had to walk one behind the other.",
    options: [
      { text: "narrow", points: 2 },
      { text: "small", points: 1 },
      { text: "steep", points: 0 },
      { text: "uneven", points: 0 },
    ],
    explanation: "A path with room for only one person at a time is narrow.",
    definition: "Not wide; there is only a little space from side to side.",
    example: "The narrow bridge fit only one bike.",
    reviewNote: "Steep and uneven are honest path words that fit a hiking sentence, but neither forces walkers into single file. Small is the right direction and scores one, yet it lumps every dimension together instead of naming width. Walking one behind the other is about width alone, so narrow is uniquely right. Five and six letters across all four, all plain adjectives of the same frequency band, no stem echo, no moral word, no silly option.",
  },
  {
    id: "fg-12", d: 3, prompt: "The towel was still ___ after hanging outside all night in the rain.",
    options: [
      { text: "soaked", points: 2 },
      { text: "damp", points: 1 },
      { text: "frozen", points: 0 },
      { text: "neat", points: 0 },
    ],
    explanation: "A whole night of rain leaves a towel soaked, which is far wetter than damp.",
    definition: "Completely wet, all the way through.",
    example: "My socks got soaked in the big puddle.",
    reviewNote: "Frozen suits a cold night and neat suits a laundry basket, so both are believable in a close sentence and neither follows from rain. Damp earns one because it is on the wet scale, yet damp means only slightly wet. All night in the rain is the evidence for the far end of that scale, so soaked is uniquely right. Four to six letters, all everyday adjectives, key absent from the stem, no elaboration gradient and nothing absurd.",
  },
  {
    id: "fg-13", d: 3, prompt: "The waiting room was so ___ that people stood shoulder to shoulder along the walls.",
    options: [
      { text: "crowded", points: 2 },
      { text: "busy", points: 1 },
      { text: "warm", points: 0 },
      { text: "peaceful", points: 0 },
    ],
    explanation: "Too many people packed into one room is crowded.",
    definition: "So full of people that there is hardly any room.",
    example: "The bus was crowded on the way to the zoo.",
    reviewNote: "Warm and peaceful are real descriptions of a waiting room and work in a nearby sentence, but neither makes anyone stand along the walls. Busy is the right direction and takes one, yet a busy room is one with a lot going on and can still have empty chairs. Standing shoulder to shoulder is the evidence that the space itself has run out, so crowded is uniquely right. Four to eight letters, all plain adjectives, same register, and spotless was moved out so it no longer sits in two items in a row.",
  },
  {
    id: "fg-14", d: 3, prompt: "The kitchen floor was so ___ that Aoife slid all the way across it in her socks.",
    options: [
      { text: "slippery", points: 2 },
      { text: "smooth", points: 1 },
      { text: "sticky", points: 0 },
      { text: "spotless", points: 0 },
    ],
    explanation: "A floor you can slide right across in socks is slippery.",
    definition: "So smooth or wet that you might slide and fall.",
    example: "The rocks by the stream are slippery.",
    reviewNote: "Sticky is the opposite effect and spotless is about cleanliness, yet both are genuine floor words that fit a similar sentence, so neither is a throwaway. Smooth scores one because a smooth floor helps, yet a smooth rug or a smooth wooden board can still grip. Sliding all the way across is the evidence for no grip at all, so slippery is uniquely right. Six to eight letters, matched register, key never appears in the stem.",
  },
  {
    id: "fg-15", d: 3, prompt: "The medicine tasted so ___ that she needed a spoonful of honey right after.",
    options: [
      { text: "bitter", points: 2 },
      { text: "strong", points: 1 },
      { text: "chalky", points: 0 },
      { text: "sugary", points: 0 },
    ],
    explanation: "A sharp taste that sweetness has to cover up is bitter.",
    definition: "A strong, sharp taste that is not sweet, like dark chocolate.",
    example: "This lemon peel tastes bitter.",
    reviewNote: "Chalky is a true medicine texture and sugary fits a syrup, so both are plausible in a neighboring sentence and neither explains reaching for honey. Strong takes one because it is on the taste scale, yet strong describes how much flavor there is rather than which flavor. Honey is sweet, and sweetness is the cure for one taste in particular, so bitter is uniquely right. All four are six letter adjectives in the same register.",
  },
  // d4: everyday adjectives at the extreme end, about age 8. The 1 point word
  // is the mild version of the same scale; the sentence names the extreme.
  {
    id: "fg-16", d: 4, prompt: "By the end of the long hike Mia was so ___ that she fell asleep at the table.",
    options: [
      { text: "exhausted", points: 2 },
      { text: "tired", points: 1 },
      { text: "dizzy", points: 0 },
      { text: "impatient", points: 0 },
    ],
    explanation: "Falling asleep sitting at the table shows Mia was exhausted, far past ordinary tired.",
    definition: "So tired that you have no energy left at all.",
    example: "After the long swim, I felt exhausted.",
    reviewNote: "Dizzy and impatient are believable after a long hike and each fits a close sentence, but neither puts anyone to sleep at a table. Tired is on the right scale and earns one, yet plenty of tired people finish dinner awake. Falling asleep at the table is the evidence for the far end of the scale, so exhausted is uniquely right. All four run five to nine letters, all plain feeling adjectives, no moral word and no silly option.",
  },
  {
    id: "fg-17", d: 4, prompt: "Dad was so ___ about the deep scratch on his new car that he could barely speak.",
    options: [
      { text: "furious", points: 2 },
      { text: "annoyed", points: 1 },
      { text: "puzzled", points: 0 },
      { text: "anxious", points: 0 },
    ],
    explanation: "Anger big enough to take your words away is being furious.",
    definition: "Very, very angry.",
    example: "She was furious when her tower got knocked down.",
    reviewNote: "Puzzled and anxious are real reactions to damage on a car and both suit a nearby sentence, but neither leaves a person unable to speak. Annoyed is on the anger scale and scores one, yet annoyed people usually have plenty to say. Barely able to speak is the evidence for the top of that scale, so furious is uniquely right. All four are seven letter feeling adjectives in the same register, with no stem echo and nothing cruel.",
  },
  {
    id: "fg-18", d: 4, prompt: "The hikers had eaten nothing since sunrise, so by dinner they were ___.",
    options: [
      { text: "starving", points: 2 },
      { text: "hungry", points: 1 },
      { text: "sleepy", points: 0 },
      { text: "homesick", points: 0 },
    ],
    explanation: "A whole day with no food leaves you starving, which is much more than hungry.",
    definition: "Extremely hungry, like you have not eaten for a long time.",
    example: "After soccer practice, I was starving for dinner.",
    reviewNote: "Sleepy and homesick are true of many long days out and each works in a close sentence, but the clause here is about food only. Hungry is the right scale and takes one, yet you can be hungry an hour after lunch. Nothing at all since sunrise is the evidence for the extreme, so starving is uniquely right. Six to eight letters, all everyday feeling adjectives, key never appears in the stem, and no option is absurd or babyish.",
  },
  {
    id: "fg-19", d: 4, prompt: "The wind off the sea was ___, and their fingers ached even inside their mittens.",
    options: [
      { text: "freezing", points: 2 },
      { text: "chilly", points: 1 },
      { text: "constant", points: 0 },
      { text: "steady", points: 0 },
    ],
    explanation: "Cold that makes fingers ache even inside mittens is freezing.",
    definition: "So cold that it feels like ice.",
    example: "The pool water was freezing this morning.",
    reviewNote: "Constant and steady are honest descriptions of a sea wind and fit a neighboring sentence, but neither makes fingers hurt. Chilly is on the cold scale and earns one, yet mittens are enough for chilly. Aching fingers even inside mittens is the evidence for the far end of that scale, so freezing is uniquely right. The stem was rewritten so the blank sits in a plain predicate slot every option fills naturally. Six to eight letters, all plain weather adjectives, no intensifier before the blank.",
  },
  {
    id: "fg-20", d: 4, prompt: "After squeezing under the porch, his shirt was ___ from the collar to the hem.",
    options: [
      { text: "filthy", points: 2 },
      { text: "dirty", points: 1 },
      { text: "damp", points: 0 },
      { text: "torn", points: 0 },
    ],
    explanation: "Covered in muck from top to bottom is filthy, which is far dirtier than dirty.",
    definition: "Very, very dirty.",
    example: "The dog came back filthy from the muddy field.",
    reviewNote: "Damp and torn are real things that happen to a shirt under a porch and both suit a close sentence, but neither is about muck. Dirty is the right scale and scores one, yet one grass stain makes a shirt dirty. From the collar to the hem is the evidence that every part is covered, so filthy is uniquely right. Five to eight letters, all everyday adjectives, same register, no moral word and no color word.",
  },
  // d5: feelings and qualities, about age 9. The sentence supplies the
  // behavior; the child names the shade of feeling that behavior shows.
  {
    id: "fg-21", d: 5, prompt: "She had practiced for weeks, yet her hands still shook, because she felt ___ about the recital.",
    options: [
      { text: "nervous", points: 2 },
      { text: "uneasy", points: 1 },
      { text: "eager", points: 0 },
      { text: "curious", points: 0 },
    ],
    explanation: "Shaking hands just before you perform is what feeling nervous looks like.",
    definition: "Worried and a little scared about something that is coming.",
    example: "I felt nervous before my first swimming lesson.",
    reviewNote: "Eager and curious are genuine feelings before a recital and both fit a close sentence, but neither makes hands shake. Uneasy is the right direction and earns one, yet uneasy is a vague background discomfort with no particular event attached. Shaking hands tied to one coming performance is the evidence, so nervous is uniquely right. Six and seven letters across all four, all plain feeling adjectives, key absent from the stem, nothing moralized.",
  },
  {
    id: "fg-22", d: 5, prompt: "Nadia had only two cookies left, and she handed one to her cousin, which was ___ of her.",
    options: [
      { text: "generous", points: 2 },
      { text: "kind", points: 1 },
      { text: "polite", points: 0 },
      { text: "sensible", points: 0 },
    ],
    explanation: "Giving away half of the little you have left is generous.",
    definition: "Happy to share and give things to others.",
    example: "My generous friend shared her crayons with everyone.",
    reviewNote: "Polite and sensible are real ways to describe an action and both suit a neighboring sentence, but sharing your last food is neither good manners nor a shrewd move. Kind is the right direction and scores one, yet holding a door is kind too. Only two left and she gave one away is the evidence about cost to herself, so generous is uniquely right. Four to eight letters, all adjectives, and no moral cue sits in the key alone since kind and polite carry it too.",
  },
  {
    id: "fg-23", d: 5, prompt: "Even after everyone showed him the rule in the book, Sam would not change his answer, because he can be ___ about things.",
    options: [
      { text: "stubborn", points: 2 },
      { text: "determined", points: 1 },
      { text: "forgetful", points: 0 },
      { text: "confused", points: 0 },
    ],
    explanation: "Refusing to change your mind even after being shown the rule is being stubborn.",
    definition: "Not willing to change your mind, even when you should.",
    example: "The stubborn goat would not move off the path.",
    reviewNote: "Forgetful and confused would each explain a mistaken answer and both work in a close sentence, but neither explains refusing after the rule was shown. Determined takes one because it names sticking to something, yet determined people bend when the facts arrive. Even after everyone showed him is the evidence, so stubborn is uniquely right. The intensifier was dropped from the stem so nothing is picked on grammar. Eight to ten letters, syllables run two, three, three and two so the key is not the odd one out, and the key is not the longest option.",
  },
  {
    id: "fg-24", d: 5, prompt: "Nana knitted her a scarf, and Aoife wrote a card to tell her how ___ she felt.",
    options: [
      { text: "grateful", points: 2 },
      { text: "delighted", points: 1 },
      { text: "surprised", points: 0 },
      { text: "impressed", points: 0 },
    ],
    explanation: "Writing a card to thank the person who gave you something shows you feel grateful.",
    definition: "Feeling thankful when someone does something nice for you.",
    example: "I am grateful for my warm blanket.",
    reviewNote: "Surprised and impressed are believable reactions to a handmade scarf and each fits a nearby sentence, but neither is aimed at the giver. Delighted earns one because it is warm and true, yet it is about the scarf rather than about Nana. Writing a card to tell her is the evidence that the feeling points back at the person, so grateful is uniquely right. Eight and nine letters, all feeling adjectives, matched register, no stem echo.",
  },
  {
    id: "fg-25", d: 5, prompt: "The door banged shut behind her without any warning, and she jumped, feeling ___.",
    options: [
      { text: "startled", points: 2 },
      { text: "surprised", points: 1 },
      { text: "annoyed", points: 0 },
      { text: "delighted", points: 0 },
    ],
    explanation: "Jumping at a bang you never saw coming is being startled.",
    definition: "Suddenly surprised or a little scared by something unexpected.",
    example: "The loud pop startled the sleepy puppy.",
    reviewNote: "Annoyed and delighted are real feelings after a door bangs and each fits a close sentence, but neither explains why she jumped. Surprised is the right direction and earns one, yet you can be surprised slowly by news that arrives in a letter. Banged shut without any warning and she jumped is the evidence for a fright that lands in one instant, so startled is uniquely right. Seven to nine letters, all feeling adjectives in one register, key absent from the stem, nothing moralized and nothing cruel.",
  },
  // d6: the same skill one shade finer, about age 10. Both credited words are
  // adult vocabulary, so the choice cannot be made on register.
  {
    id: "fg-26", d: 6, prompt: "Tom did not want the spicy stew at all, but he took one small bite to be polite, so he was ___.",
    options: [
      { text: "reluctant", points: 2 },
      { text: "hesitant", points: 1 },
      { text: "puzzled", points: 0 },
      { text: "impatient", points: 0 },
    ],
    explanation: "Doing the thing you truly did not want to do is being reluctant.",
    definition: "Not wanting to do something, so you are slow to do it.",
    example: "He was reluctant to jump into the cold lake.",
    reviewNote: "Puzzled and impatient are real states at a dinner table and each suits a neighboring sentence, but neither is about not wanting the food. Hesitant scores one because it names holding back, yet hesitating is a pause that can end either way. He did not want it at all and still took a bite is the evidence, so reluctant is uniquely right. Seven to nine letters, all feeling adjectives, and the key is not the only long word.",
  },
  {
    id: "fg-27", d: 6, prompt: "He changed the subject every time she asked about the broken window, which made her ___.",
    options: [
      { text: "suspicious", points: 2 },
      { text: "uncertain", points: 1 },
      { text: "indifferent", points: 0 },
      { text: "defensive", points: 0 },
    ],
    explanation: "Dodging the same question again and again makes people suspicious that something is being hidden.",
    definition: "Thinking something is not quite right, or that someone is hiding something.",
    example: "The dog gave the vacuum a suspicious look.",
    reviewNote: "Indifferent and defensive are believable reactions to a person changing the subject and both fit a close sentence, but she has nothing to defend and she plainly still cares, so neither answers the dodging itself. Uncertain earns one because she is left not knowing, yet uncertainty has no direction. Every time she asked is the evidence for a pattern that points at him, so suspicious is uniquely right. Nine and ten letters across the four, all feeling adjectives, key absent from the stem.",
  },
  {
    id: "fg-28", d: 6, prompt: "The zipper stuck for the tenth time, and Aoife threw the jacket down because she was so ___.",
    options: [
      { text: "frustrated", points: 2 },
      { text: "irritated", points: 1 },
      { text: "embarrassed", points: 0 },
      { text: "surprised", points: 0 },
    ],
    explanation: "Being blocked over and over by the same thing leaves you frustrated.",
    definition: "Upset because something keeps not working and you cannot fix it.",
    example: "She felt frustrated when her kite would not fly.",
    reviewNote: "Embarrassed and surprised are honest feelings in a similar sentence, but a stuck zipper on the tenth try is neither shameful nor unexpected. Irritated is the right direction and takes one, yet irritation is about a single annoyance rather than a blocked goal. For the tenth time is the evidence for repeated blocking, so frustrated is uniquely right. Nine to eleven letters, all feeling adjectives in the same register, and the key is not the longest.",
  },
  {
    id: "fg-29", d: 6, prompt: "The lost puppy trotted up the path at last, and Dad let out a long breath because he felt ___.",
    options: [
      { text: "relieved", points: 2 },
      { text: "pleased", points: 1 },
      { text: "confused", points: 0 },
      { text: "hopeful", points: 0 },
    ],
    explanation: "That long breath out when a worry finally ends is feeling relieved.",
    definition: "Happy because a worry is finally over.",
    example: "I was relieved when I found my lost shoe.",
    reviewNote: "Confused and hopeful are real feelings around a missing pet and each fits a close sentence, but nothing here is muddled and hopeful belongs to the waiting rather than to the end of it. Pleased scores one because he is glad, yet pleased would fit a puppy that had never been lost. At last plus the long breath is the evidence that a fear lifted, so relieved is uniquely right. Seven and eight letters throughout.",
  },
  {
    id: "fg-30", d: 6, prompt: "She had swum that distance twenty times in practice, so she stepped onto the starting block feeling ___.",
    options: [
      { text: "confident", points: 2 },
      { text: "certain", points: 1 },
      { text: "anxious", points: 0 },
      { text: "distracted", points: 0 },
    ],
    explanation: "Twenty practice swims give you confident trust in what your own body can do.",
    definition: "Sure that you can do something well.",
    example: "After practicing, she felt confident about her song.",
    reviewNote: "Anxious and distracted are genuine race day feelings and both suit a nearby sentence, but neither comes from having practiced. Certain is the right direction and earns one, yet no swimmer can be certain of a race, only sure of herself. Twenty times in practice is the evidence about her own ability, so confident is uniquely right. Lengths run seven, seven, nine and ten so the key is neither the longest nor the odd one out, and there is no stem echo.",
  },
  // d7: academic adjectives, about age 11. All four options are words an
  // adult would use; only the sentence separates them.
  {
    id: "fg-31", d: 7, prompt: "The hollow eggshell broke the moment her thumb pressed it, showing just how ___ it was.",
    options: [
      { text: "fragile", points: 2 },
      { text: "delicate", points: 1 },
      { text: "flexible", points: 0 },
      { text: "polished", points: 0 },
    ],
    explanation: "Something that breaks under the lightest press is fragile.",
    definition: "Easy to break, so you must be very gentle with it.",
    example: "Carry the fragile glass bowl with two hands.",
    reviewNote: "Flexible and polished are true of other shells and objects and each fits a close sentence, but flexible things bend instead of breaking and polish has nothing to do with strength. Delicate scores one because it is in the same family, yet delicate is mainly about being finely made and a delicate chain does not break at a touch. Broke the moment her thumb pressed it is the evidence, so fragile is uniquely right. Seven and eight letters, matched register.",
  },
  {
    id: "fg-32", d: 7, prompt: "Even after being carried back to his bed four times, the puppy kept scratching at the door, so he was ___.",
    options: [
      { text: "persistent", points: 2 },
      { text: "insistent", points: 1 },
      { text: "affectionate", points: 0 },
      { text: "forgetful", points: 0 },
    ],
    explanation: "Trying again after being stopped four separate times is being persistent.",
    definition: "Keeps trying again and again and does not give up.",
    example: "The persistent bird kept pecking at the feeder.",
    reviewNote: "Affectionate and forgetful are believable of any puppy and both fit a neighboring sentence, but a puppy who wants the door does not want a cuddle and nothing here is forgotten. Insistent earns one because it names demanding what you want, yet insisting happens in one moment while the sentence spans four. Carried back four times and still going is the evidence for continuing through setbacks, so persistent is uniquely right. The intensifier was dropped from the stem.",
  },
  {
    id: "fg-33", d: 7, prompt: "The hill never rose sharply anywhere, and the climb was so ___ that we barely noticed we were going up.",
    options: [
      { text: "gradual", points: 2 },
      { text: "easy", points: 1 },
      { text: "muddy", points: 0 },
      { text: "unusual", points: 0 },
    ],
    explanation: "A rise so slow and even that you hardly notice it is gradual.",
    definition: "Happening slowly, a little bit at a time.",
    example: "The path had a gradual climb up the hill.",
    reviewNote: "Muddy and unusual are honest trail words that fit a close sentence, but a muddy path can still rise evenly and an unusual one would be noticed at once. Easy takes one because a rise like this is not hard work, yet easy measures the effort while the sentence measures the rise. Barely noticed we were going up is the evidence for change spread evenly over distance, so gradual is uniquely right. Four to seven letters, all plain adjectives, no stem echo.",
  },
  {
    id: "fg-34", d: 7, prompt: "The old truck started on the first try every single morning for twenty years, so Grandpa called it ___.",
    options: [
      { text: "reliable", points: 2 },
      { text: "sturdy", points: 1 },
      { text: "valuable", points: 0 },
      { text: "roomy", points: 0 },
    ],
    explanation: "Something you can count on every single time is reliable.",
    definition: "You can always count on it to work or to help.",
    example: "Our reliable old clock is never late.",
    reviewNote: "Valuable and roomy are real ways to praise a truck and both fit a nearby sentence, but neither follows from starting on the first try. Sturdy scores one because it points at good build, yet a sturdy engine can still refuse to start. Every single morning for twenty years is the evidence about dependability over time, so reliable is uniquely right. Six to eight letters, all adjectives of the same frequency band, key absent from the stem.",
  },
  {
    id: "fg-35", d: 7, prompt: "Nobody had to guess who ate the pie, because the crumbs on the puppy's nose made it ___.",
    options: [
      { text: "obvious", points: 2 },
      { text: "likely", points: 1 },
      { text: "amusing", points: 0 },
      { text: "curious", points: 0 },
    ],
    explanation: "An answer nobody even has to think about is obvious.",
    definition: "Very easy to see or understand.",
    example: "It was obvious that the puppy wanted a treat.",
    reviewNote: "Amusing is true of the picture and curious means strange, yet both are natural words in a close sentence and neither answers what the crumbs did to the question. Likely earns one because the crumbs really do point at the puppy, yet likely still leaves room for somebody else. Nobody had to guess is the evidence that no working out was needed at all, so obvious is uniquely right. Six and seven letters, same register throughout.",
  },
  // d8: academic adjectives one step finer, about age 12. The 1 point word is
  // a real synonym that misses one feature the sentence supplies.
  {
    id: "fg-36", d: 8, prompt: "Blackberries were so ___ along the lane that we filled four buckets and still left most of them behind.",
    options: [
      { text: "abundant", points: 2 },
      { text: "common", points: 1 },
      { text: "fragrant", points: 0 },
      { text: "juicy", points: 0 },
    ],
    explanation: "So many that four buckets hardly make a dent means the berries were abundant.",
    definition: "There is lots and lots of it, more than enough.",
    example: "Apples were abundant on the farm this fall.",
    reviewNote: "Fragrant and juicy both describe real ripe bramble, so both fit a neighboring sentence and neither says how many berries there are. Common takes one because it means often found, yet common is about how widely a thing occurs rather than how much of it is here now. Filled four buckets and left most behind is the evidence for sheer quantity, so abundant is uniquely right. Six to nine letters, matched register.",
  },
  {
    id: "fg-37", d: 8, prompt: "He looked straight at her, then pushed the vase off the shelf with one finger, so what he did was ___.",
    options: [
      { text: "deliberate", points: 2 },
      { text: "planned", points: 1 },
      { text: "sudden", points: 0 },
      { text: "mysterious", points: 0 },
    ],
    explanation: "Choosing to do something while watching the other person makes the act deliberate.",
    definition: "Done on purpose, not by accident.",
    example: "Her careful, deliberate steps crossed the icy path.",
    reviewNote: "Sudden and mysterious are ordinary words for an act with a broken vase and each fits a close sentence, but he looked first and pushed with one finger, so nothing was hurried and nothing was hidden. Planned scores one because it also rules out accident, yet planning means working it out beforehand and the sentence shows only the moment. Looked straight at her then pushed is the evidence for on purpose, so deliberate is uniquely right.",
  },
  {
    id: "fg-38", d: 8, prompt: "The rope walkway was only meant to last until the new bridge opened, so everyone knew it was ___.",
    options: [
      { text: "temporary", points: 2 },
      { text: "fleeting", points: 1 },
      { text: "risky", points: 0 },
      { text: "expensive", points: 0 },
    ],
    explanation: "Something built to be replaced later is temporary.",
    definition: "Lasting only a short time, not forever.",
    example: "The tent was our temporary home for the weekend.",
    reviewNote: "Risky and expensive are true of many rope walkways and both fit a nearby sentence, but neither follows from the clause about the new bridge. Fleeting earns one because it also means short lasting, yet fleeting belongs to moments and feelings while this sentence is about a structure standing in for another. Only meant to last until the new bridge opened is the evidence, so temporary is uniquely right. Five to nine letters, all adjectives, no stem echo and no register cue.",
  },
  {
    id: "fg-39", d: 8, prompt: "You can hike without a map or a hat, but water is ___ on a day this hot.",
    options: [
      { text: "essential", points: 2 },
      { text: "useful", points: 1 },
      { text: "optional", points: 0 },
      { text: "heavy", points: 0 },
    ],
    explanation: "Something you truly cannot go without is essential.",
    definition: "So important that you really need it.",
    example: "Sleep is essential for a growing body.",
    reviewNote: "Optional and heavy are real words about supplies on a hike and each fits a close sentence, but the contrast with the map and the hat rules out optional and the weight of a bottle is not the point. Useful takes one because water certainly helps, yet the map is useful too and the sentence has just set it aside. The contrast between what you can skip and what you cannot is the evidence, so essential is uniquely right.",
  },
  {
    id: "fg-40", d: 8, prompt: "Guessing at half a cup will ruin the cake, so a recipe needs measurements that are ___.",
    options: [
      { text: "precise", points: 2 },
      { text: "correct", points: 1 },
      { text: "sensible", points: 0 },
      { text: "familiar", points: 0 },
    ],
    explanation: "Measurements that have to be exact to the last spoonful are precise.",
    definition: "Exactly right, with no mistakes, down to the tiniest bit.",
    example: "The builder took precise measurements of the window.",
    reviewNote: "Sensible and familiar are true of good recipes and both fit a neighboring sentence, but neither is about exactness. Correct scores one because a mistaken amount does ruin a cake, yet correct only means not mistaken and about half a cup can be correct in a stew. Guessing at half a cup will ruin it is the evidence for fine exactness rather than mere accuracy, so precise is uniquely right. Seven and eight letters throughout, same register.",
  },
  // d9: precise academic vocabulary, about age 13. Abstract nouns sit beside
  // abstract nouns and abstract adjectives beside abstract adjectives, so no
  // option can be dropped for being a physical object.
  {
    id: "fg-41", d: 9, prompt: "Nobody could prove it either way, but his story fit every fact they already knew, so they called it ___.",
    options: [
      { text: "plausible", points: 2 },
      { text: "possible", points: 1 },
      { text: "peculiar", points: 0 },
      { text: "confusing", points: 0 },
    ],
    explanation: "A story that fits all the known facts sounds plausible, even before anyone can prove it.",
    definition: "Easy to believe, because it could really be true.",
    example: "Her reason for being late sounded plausible.",
    reviewNote: "Peculiar and confusing are real verdicts on a story and each fits a close sentence, but neither follows from a story that fits every fact. Possible earns one because it also survives the lack of proof, yet possible only means not ruled out and a wild tale can be possible. Fit every fact they already knew is the evidence for positive support, so plausible is uniquely right. Eight and nine letters, all adjectives, same register, no stem echo.",
  },
  {
    id: "fg-42", d: 9, prompt: "Before she touched a single seed, Rosa wrote down that the plants under the lamp would grow taller, and that sentence was her ___.",
    options: [
      { text: "hypothesis", points: 2 },
      { text: "theory", points: 1 },
      { text: "conclusion", points: 0 },
      { text: "reason", points: 0 },
    ],
    explanation: "The testable sentence you write before an experiment is your hypothesis.",
    definition: "A smart guess you make before you test to find out.",
    example: "My hypothesis is that plants grow faster in sunlight.",
    reviewNote: "Conclusion and reason are genuine science words and each fits a nearby sentence, but a conclusion comes after the results and a reason says why she expects something rather than what she expects. Theory scores one because it names an idea about how things work, yet a theory is a broad explanation already backed by evidence. Before she touched a single seed is the evidence that this is the statement written to be tested, so hypothesis is uniquely right. All four are abstract nouns of six to ten letters.",
  },
  {
    id: "fg-43", d: 9, prompt: "Every label on her rock collection carried the same neat handwriting, the date, and the exact spot the stone was found, which showed how ___ she was.",
    options: [
      { text: "meticulous", points: 2 },
      { text: "organized", points: 1 },
      { text: "ambitious", points: 0 },
      { text: "adventurous", points: 0 },
    ],
    explanation: "Caring about every tiny detail like that is being meticulous.",
    definition: "Very careful to get every tiny detail exactly right.",
    example: "He was meticulous when he glued the model ship.",
    reviewNote: "Ambitious and adventurous are believable of a rock collector and both fit a close sentence, but neither is shown by the labels themselves. Organized takes one because the collection clearly has a system, yet organized is about arrangement and a tidy box can hold blank labels. The date and the exact spot on every single label is the evidence about fine detail, so meticulous is uniquely right. Nine to eleven letters, all character adjectives, key not the longest.",
  },
  {
    id: "fg-44", d: 9, prompt: "Losing her turn on the trampoline was the ___ she had been warned about for breaking the same rule twice.",
    options: [
      { text: "consequence", points: 2 },
      { text: "result", points: 1 },
      { text: "reminder", points: 0 },
      { text: "explanation", points: 0 },
    ],
    explanation: "What follows from a choice you made, and follows because you made it, is the consequence.",
    definition: "Something that happens because of what you did.",
    example: "A tummy ache was the consequence of too much candy.",
    reviewNote: "Reminder and explanation are real nouns for this slot and each fits a nearby sentence, but a lost turn does not explain the rule breaking and it is more than a nudge to remember. Result earns one because it also names what came after, yet a result can follow anything at all, including luck. She had been warned about it is the evidence that this outcome was named in advance as what the rule breaking would bring, so consequence is uniquely right. All four are abstract nouns.",
  },
  {
    id: "fg-45", d: 9, prompt: "The note said to meet by the tall tree, but there were two tall trees, so the message was ___.",
    options: [
      { text: "ambiguous", points: 2 },
      { text: "unclear", points: 1 },
      { text: "anonymous", points: 0 },
      { text: "playful", points: 0 },
    ],
    explanation: "A message that can honestly be read two different ways is ambiguous.",
    definition: "Could mean more than one thing, so it is not clear.",
    example: "The ambiguous sign could point to either door.",
    reviewNote: "Anonymous and playful are real descriptions of a note and both fit a close sentence, but neither has anything to do with there being two trees. Unclear scores one because the reader is left not knowing, yet unclear covers messy handwriting too. Two tall trees is the evidence that the words have exactly two good readings, so ambiguous is uniquely right. Seven to ten letters, all adjectives, matched register, key absent from the stem.",
  },
  // d10: the finest distinctions in the bank, about age 13. Both credited
  // options are academic words; only the evidence in the sentence separates.
  {
    id: "fg-46", d: 10, prompt: "Once the last stone at the bottom slipped, the whole wall coming down was ___.",
    options: [
      { text: "inevitable", points: 2 },
      { text: "predictable", points: 1 },
      { text: "silent", points: 0 },
      { text: "regrettable", points: 0 },
    ],
    explanation: "Something that can no longer be stopped by anyone is inevitable.",
    definition: "Sure to happen; there is no way to stop it.",
    example: "When the clouds turn dark, rain seems inevitable.",
    reviewNote: "Silent and regrettable are honest descriptions of a collapsing wall and each fits a nearby sentence, but neither says anything about whether it had to happen. Predictable takes one because anyone watching could see it coming, yet being easy to foresee is not the same as being impossible to stop. Once the last stone slipped is the evidence that the outcome was locked in, so inevitable is uniquely right. Six to eleven letters, all adjectives, key not the longest.",
  },
  {
    id: "fg-47", d: 10, prompt: "He never asked whether she could swim and simply took it for granted, and that ___ nearly ended in trouble.",
    options: [
      { text: "assumption", points: 2 },
      { text: "guess", points: 1 },
      { text: "warning", points: 0 },
      { text: "suggestion", points: 0 },
    ],
    explanation: "Treating something as true without ever checking it is an assumption.",
    definition: "Something you believe is true without checking first.",
    example: "My assumption was that the store opened at nine.",
    reviewNote: "Warning and suggestion are real nouns for something said between two people and each fits a close sentence, but he said nothing at all. Guess earns one because he also did not know, yet a guess is made knowing you might be mistaken, and he was not weighing anything. Never asked and simply took it for granted is the evidence, so assumption is uniquely right. All four are abstract nouns of five to ten letters in one register.",
  },
  {
    id: "fg-48", d: 10, prompt: "Three of his fish stories had already turned out to be invented, so this time the family listened politely and asked for proof, staying ___.",
    options: [
      { text: "skeptical", points: 2 },
      { text: "doubtful", points: 1 },
      { text: "hopeful", points: 0 },
      { text: "indifferent", points: 0 },
    ],
    explanation: "Holding back belief until proof arrives is staying skeptical.",
    definition: "Not ready to believe something until you see proof.",
    example: "Mom was skeptical that the dog ate my homework.",
    reviewNote: "Hopeful and indifferent are real stances a listener can take and both fit a nearby sentence, but the family neither took his side nor stopped caring, since they asked for proof. Doubtful scores one because it also withholds belief, yet doubtful simply leans against believing. Listened politely and asked for proof is the evidence for a stance that would change given evidence, so skeptical is uniquely right.",
  },
  {
    id: "fg-49", d: 10, prompt: "He said he had never been inside the shed, then described the fresh paint on its walls, and the family noticed the ___.",
    options: [
      { text: "contradiction", points: 2 },
      { text: "mistake", points: 1 },
      { text: "exaggeration", points: 0 },
      { text: "coincidence", points: 0 },
    ],
    explanation: "Two statements that cannot both be true at once make a contradiction.",
    definition: "When two things someone says cannot both be true.",
    example: "Saying 'I love it' and 'I hate it' is a contradiction.",
    reviewNote: "Exaggeration and coincidence are genuine nouns for something odd in a story and each fits a close sentence, but nothing here was stretched and nothing lined up by chance. Mistake earns one because something has certainly gone amiss, yet mistake covers a slip of memory or a misheard word. Never been inside set against describing the paint inside is the evidence for two claims that clash, so contradiction is uniquely right. All four are abstract nouns.",
  },
  {
    id: "fg-50", d: 10, prompt: "Every single cousin raised a hand for pizza, so the choice was ___.",
    options: [
      { text: "unanimous", points: 2 },
      { text: "popular", points: 1 },
      { text: "spontaneous", points: 0 },
      { text: "hasty", points: 0 },
    ],
    explanation: "When everybody agrees with no one left out, the choice is unanimous.",
    definition: "When everyone agrees, with nobody saying no.",
    example: "The vote for a movie night was unanimous.",
    reviewNote: "Spontaneous and hasty are real ways to describe a group decision and both fit a nearby sentence, but neither follows from counting the hands. Popular takes one because plenty of people wanted it, yet popular allows a few holdouts. Every single cousin is the evidence that not one person differed, so unanimous is uniquely right. Seven to ten letters, all adjectives, same register, no stem echo, and no option carries a moral cue.",
  },
  // fg-51..fg-80 added 2026-09-12 (variety pass): five more per tier d5-d10 so
  // cross-session avoidance has fresh words at her tiers.
  {
    id: "fg-51", d: 5, prompt: "\"I guess I can share,\" Leo ___, so quietly that his sister had to lean closer to hear.",
    options: [
      { text: "mumbled", points: 2 },
      { text: "said", points: 1 },
      { text: "announced", points: 0 },
      { text: "cheered", points: 0 },
    ],
    explanation: "Words that come out so quietly that someone has to lean in are mumbled, not only said.",
    definition: "Said words quietly and not clearly, so they were hard to hear.",
    example: "Dad mumbled good morning with his eyes half shut.",
    reviewNote: "Announced and cheered are real speaking verbs a child might try, but both are loud, and the sentence says his sister had to lean closer to hear. Said is true and earns one point, yet it names no manner at all. The quiet, grudging half sentence is the evidence. All four are past tense speech verbs of similar length; no stem echo, no article before the blank.",
  },
  {
    id: "fg-52", d: 5, prompt: "When the power went out during the blizzard, the neighbors shared candles, soup and blankets, and their ___ got everyone through the night.",
    options: [
      { text: "teamwork", points: 2 },
      { text: "help", points: 1 },
      { text: "courage", points: 0 },
      { text: "creativity", points: 0 },
    ],
    explanation: "Neighbors sharing what each of them had is teamwork, which is more than just help.",
    definition: "People working together and helping each other to get something done.",
    example: "It took teamwork to carry the big couch upstairs.",
    reviewNote: "Courage and creativity are both things a dark snowy night can call for, so a child could try them, but neither describes neighbors pooling candles, soup and blankets. Help is true and scores one, yet it misses that everyone pitched in together. The sharing between neighbors is the evidence. All four are abstract nouns; the key is not the longest option.",
  },
  {
    id: "fg-53", d: 5, prompt: "Mina felt ___ as she stood a little taller and kept admiring the birdhouse she had built all by herself.",
    options: [
      { text: "proud", points: 2 },
      { text: "happy", points: 1 },
      { text: "bored", points: 0 },
      { text: "lonely", points: 0 },
    ],
    explanation: "Standing taller and admiring something she made herself shows she felt proud, not only happy.",
    definition: "Feeling good about something you did well.",
    example: "Leo was proud of his tall block tower.",
    reviewNote: "Lonely tempts because of all by herself, and bored is a real feeling for a child, but standing taller and admiring her own work fits neither. Happy is true and scores one, yet it misses that the good feeling comes from something she did. All four are feeling adjectives of similar length; no stem echo.",
  },
  {
    id: "fg-54", d: 5, prompt: "The kitten ___ behind the couch whenever the vacuum roars to life and only comes out once it is quiet again.",
    options: [
      { text: "hides", points: 2 },
      { text: "stays", points: 1 },
      { text: "sleeps", points: 0 },
      { text: "plays", points: 0 },
    ],
    explanation: "Going behind the couch when the vacuum is loud and coming out only when it stops is hiding, not just staying.",
    definition: "Goes to a spot where nobody can see or find it.",
    example: "My cat hides under the bed during storms.",
    reviewNote: "Sleeps and plays are everyday kitten verbs and a kitten really might do either behind a couch, but neither explains why it only comes out once the noise stops. Stays is right about the place and scores one, yet it misses the reason. The roaring vacuum is the evidence. All four are present tense verbs of similar length.",
  },
  {
    id: "fg-55", d: 5, prompt: "Even though Ben's tower fell down four times, he stayed ___ and kept building it again with a smile.",
    options: [
      { text: "patient", points: 2 },
      { text: "calm", points: 1 },
      { text: "quiet", points: 0 },
      { text: "serious", points: 0 },
    ],
    explanation: "Keeping at it with a smile after four falls shows he was patient, which is more than being calm.",
    definition: "Able to wait or keep trying without getting upset.",
    example: "Be patient while the cookies cool down.",
    reviewNote: "Quiet and serious are real ways a child can build, but neither says anything about four collapses and starting again with a smile, and serious clashes with the smile. Calm is the right direction and scores one, yet a calm child could still give up after the first fall. Four falls and a smile are the evidence. All four are quality adjectives.",
  },
  {
    id: "fg-56", d: 6, prompt: "Omar ___ the old photo for a long time, tilting it toward the window to find every face in the crowd.",
    options: [
      { text: "studied", points: 2 },
      { text: "viewed", points: 1 },
      { text: "folded", points: 0 },
      { text: "printed", points: 0 },
    ],
    explanation: "Looking for a long time and tilting the photo to pick out every face is studying it, more than viewing it.",
    definition: "Looked at something closely and carefully to learn about it.",
    example: "The detective studied the footprints in the snow.",
    reviewNote: "Folded and printed are real things people do with an old photo, but neither fits tilting it toward the window to find faces. Viewed is true and scores one, yet it misses how long and how closely he searched. The tilting and the search for every face are the evidence. All four are past tense verbs of the same length band.",
  },
  {
    id: "fg-57", d: 6, prompt: "Maya is ___ about her soccer goals: she never says how many she scored, only that the whole team played well.",
    options: [
      { text: "modest", points: 2 },
      { text: "quiet", points: 1 },
      { text: "cheerful", points: 0 },
      { text: "careless", points: 0 },
    ],
    explanation: "Never counting her own goals and praising the whole team is being modest, which says more than being quiet.",
    definition: "Not bragging or showing off about the good things you do.",
    example: "Even after winning, the modest runner thanked her friends.",
    reviewNote: "Cheerful and careless are real words for a child on a team, but neither explains keeping quiet about her own goals while praising everyone else. Quiet scores one because she does not talk about her goals, yet it misses that she is choosing not to show off. Her praise for the team is the evidence. All four are quality adjectives.",
  },
  {
    id: "fg-58", d: 6, prompt: "Ana felt ___ when her little brother got a new bike, and she kept wishing it were hers instead.",
    options: [
      { text: "jealous", points: 2 },
      { text: "upset", points: 1 },
      { text: "excited", points: 0 },
      { text: "worried", points: 0 },
    ],
    explanation: "Wishing her brother's new bike were hers is feeling jealous, a more exact word than upset.",
    definition: "Wanting something that someone else has, and feeling upset about it.",
    example: "The puppy got jealous when I petted the cat.",
    reviewNote: "Excited is what a child often feels around a new bike and worried is a real feeling, but neither fits wishing the bike belonged to her instead. Upset is the right direction and scores one, yet it does not say why. Wishing it were hers is the evidence. All four are feeling adjectives of equal length.",
  },
  {
    id: "fg-59", d: 6, prompt: "\"Okay, it was me who left the gate open,\" Theo ___, staring down at his muddy boots.",
    options: [
      { text: "admitted", points: 2 },
      { text: "replied", points: 1 },
      { text: "promised", points: 0 },
      { text: "complained", points: 0 },
    ],
    explanation: "Saying it was me about a mess you made is admitting it, which is more than replying.",
    definition: "Told the truth about something, even though it was hard to say.",
    example: "Mia admitted that she forgot to feed the fish.",
    reviewNote: "Promised and complained are real speech verbs a child could try, but his words are neither a promise nor a complaint; they own up to a mistake. Replied fits any answer and scores one, yet it misses the confession. It was me plus staring at his boots is the evidence. All four are past tense speech verbs; the key is not the longest.",
  },
  {
    id: "fg-60", d: 6, prompt: "Ruby wrote Jake a card saying she was sorry for breaking his crayon, and he taped her ___ to his wall.",
    options: [
      { text: "apology", points: 2 },
      { text: "note", points: 1 },
      { text: "invitation", points: 0 },
      { text: "drawing", points: 0 },
    ],
    explanation: "A card that says sorry is an apology; calling it a note is true but less exact.",
    definition: "Words you say or write to tell someone you are sorry.",
    example: "Tom gave his sister an apology for grabbing her toy.",
    reviewNote: "Invitation and drawing are both things a child might tape to a wall, but a card saying sorry for a broken crayon is neither. Note is true and scores one, yet it misses what the card was for. Saying she was sorry is the evidence. All four are concrete nouns; the key is not the longest option.",
  },
  {
    id: "fg-61", d: 7, prompt: "Without counting every jellybean, Noor looked at the jar and tried to ___ how many were inside.",
    options: [
      { text: "estimate", points: 2 },
      { text: "judge", points: 1 },
      { text: "measure", points: 0 },
      { text: "remember", points: 0 },
    ],
    explanation: "Working out about how many without counting each one is estimating.",
    definition: "Make a smart guess about an amount without counting exactly.",
    example: "Can you estimate how many steps it is to the park?",
    reviewNote: "Measure and remember are real things you do with numbers and jars, but you cannot remember a number you never counted, and measuring is not about how many. Judge is the right direction and scores one, yet it is vaguer about an amount. Without counting is the evidence. All four are base form verbs of similar length.",
  },
  {
    id: "fg-62", d: 7, prompt: "For science class, Kai sat by the pond each morning to ___ the tadpoles and draw how their legs grew.",
    options: [
      { text: "observe", points: 2 },
      { text: "watch", points: 1 },
      { text: "collect", points: 0 },
      { text: "feed", points: 0 },
    ],
    explanation: "Looking closely every morning so he can draw the changes is observing, a more exact word than watching.",
    definition: "Watch something carefully to notice and learn about it.",
    example: "We observe the moon every night for a week.",
    reviewNote: "Collect and feed are real things children do with tadpoles, but neither goes with sitting by the pond to draw how their legs grew. Watch is true and scores one, yet it misses the careful noticing done to record changes. Drawing the legs each morning is the evidence. All four are base form verbs.",
  },
  {
    id: "fg-63", d: 7, prompt: "Before choosing a backpack, Dev set the two side by side to ___ their size, price and pockets.",
    options: [
      { text: "compare", points: 2 },
      { text: "check", points: 1 },
      { text: "decorate", points: 0 },
      { text: "polish", points: 0 },
    ],
    explanation: "Putting two things side by side to look at size, price and pockets is comparing them.",
    definition: "Look at two or more things to see how they are alike or different.",
    example: "Let's compare our drawings to see which tree is taller.",
    reviewNote: "Decorate and polish are real things you might do to a backpack, but neither needs two of them side by side or looks at price. Check scores one because he does look at those things, yet it misses weighing one against the other. Side by side is the evidence. All four are base form verbs; the key is not the longest.",
  },
  {
    id: "fg-64", d: 7, prompt: "The weather app said rain would start at three o'clock, and the first drops fell right at three, so its forecast was ___.",
    options: [
      { text: "accurate", points: 2 },
      { text: "helpful", points: 1 },
      { text: "dramatic", points: 0 },
      { text: "gloomy", points: 0 },
    ],
    explanation: "A forecast that matched exactly what happened was accurate; helpful is true but less exact.",
    definition: "Correct and true, matching what really happens.",
    example: "The map was accurate, so we found the park easily.",
    reviewNote: "Dramatic and gloomy are words a child links with rainy weather, but they describe the weather, not whether the forecast came true. Helpful scores one because a right forecast does help, yet it misses the point that it matched. The drops falling right at three is the evidence. All four are adjectives; the key ties for longest.",
  },
  {
    id: "fg-65", d: 7, prompt: "Every year on the first snowy day, the whole family builds a snowman and drinks cocoa; it is their favorite ___.",
    options: [
      { text: "tradition", points: 2 },
      { text: "activity", points: 1 },
      { text: "adventure", points: 0 },
      { text: "recipe", points: 0 },
    ],
    explanation: "Doing the same thing every year as a family is a tradition, which is more than an activity.",
    definition: "Something a family or group does the same way, year after year.",
    example: "Pancakes on Sunday morning are a tradition at our house.",
    reviewNote: "Adventure fits a snowy day and recipe fits the cocoa, so a child could try either, but neither captures doing the same thing every single year. Activity is true and scores one, yet it misses the every year part. Every year is the evidence. All four are nouns; the key ties for longest.",
  },
  {
    id: "fg-66", d: 8, prompt: "Mateo was ___ at the frozen pond: he tapped the ice with a stick and listened for cracks before taking a single step.",
    options: [
      { text: "cautious", points: 2 },
      { text: "careful", points: 1 },
      { text: "graceful", points: 0 },
      { text: "sneaky", points: 0 },
    ],
    explanation: "Testing the ice for danger before stepping is being cautious, which is more exact than careful.",
    definition: "Very careful to stay away from danger or trouble.",
    example: "The cautious deer looked around before drinking.",
    reviewNote: "Graceful and sneaky are real ways to move across ice, but tapping for cracks before a single step is about danger, not style or secrecy. Careful is the right direction and scores one, yet cautious names the watchfulness for danger. Listening for cracks is the evidence. All four are adjectives; the key ties for longest.",
  },
  {
    id: "fg-67", d: 8, prompt: "Lia wanted the beach and Max wanted the zoo, so their ___ was the zoo in the morning and the beach after lunch.",
    options: [
      { text: "compromise", points: 2 },
      { text: "plan", points: 1 },
      { text: "argument", points: 0 },
      { text: "punishment", points: 0 },
    ],
    explanation: "When each one gets part of what they wanted, that is a compromise, not just a plan.",
    definition: "When each person gives up a little so everyone gets part of what they want.",
    example: "Taking turns on the swing was a fair compromise.",
    reviewNote: "Argument and punishment are words that often come up when two children want different things, but the sentence shows them settling it fairly. Plan is true and scores one, yet it misses that each gave up half. The zoo then the beach is the evidence. All four are nouns; the key ties for longest.",
  },
  {
    id: "fg-68", d: 8, prompt: "Rafi played piano for ten minutes every day, never skipping once, and his ___ practice helped him improve.",
    options: [
      { text: "consistent", points: 2 },
      { text: "daily", points: 1 },
      { text: "creative", points: 0 },
      { text: "difficult", points: 0 },
    ],
    explanation: "Practice that happens every day without skipping is consistent; daily is true but misses the never skipping.",
    definition: "Doing something the same steady way every time, without skipping.",
    example: "Her consistent reading made her a stronger reader.",
    reviewNote: "Creative and difficult are real words for piano practice, but the sentence says nothing about how inventive or hard it was. Daily scores one because it did happen every day, yet consistent adds the steady never skipped part. Never skipping once is the evidence. All four are adjectives; the key is longest by one letter at most.",
  },
  {
    id: "fg-69", d: 8, prompt: "Kira packs her own lunch, ties her own shoes and walks to the bus stop without asking anyone for help, because she likes being ___.",
    options: [
      { text: "independent", points: 2 },
      { text: "responsible", points: 1 },
      { text: "mischievous", points: 0 },
      { text: "competitive", points: 0 },
    ],
    explanation: "Doing things by herself without asking for help is being independent; responsible is close but misses the by herself.",
    definition: "Able to do things by yourself without needing help from others.",
    example: "The independent toddler wanted to pour her own milk.",
    reviewNote: "Mischievous and competitive are real words for a lively child, but nothing here is naughty or about winning. Responsible scores one because she does her own jobs, yet the sentence stresses doing it without asking anyone. Without asking anyone for help is the evidence. All four are eleven letter adjectives, so length gives nothing away.",
  },
  {
    id: "fg-70", d: 8, prompt: "Jonah made a poster with three good reasons to get a class pet, hoping to ___ his parents to say yes.",
    options: [
      { text: "persuade", points: 2 },
      { text: "ask", points: 1 },
      { text: "remind", points: 0 },
      { text: "surprise", points: 0 },
    ],
    explanation: "Giving good reasons so someone agrees is persuading, which is more than asking.",
    definition: "Get someone to agree with you by giving good reasons.",
    example: "I tried to persuade my brother to share his fries.",
    reviewNote: "Remind and surprise are real things a child does with parents and a poster, but you cannot remind someone to agree to something new, and a surprise needs no reasons. Ask scores one because he does want a yes, yet it leaves out the reasons. Three good reasons is the evidence. All four are base form verbs.",
  },
  {
    id: "fg-71", d: 9, prompt: "Ava climbed to the top of the slide, and from that height her ___ changed: the sandbox looked like a tiny cookie.",
    options: [
      { text: "perspective", points: 2 },
      { text: "view", points: 1 },
      { text: "attitude", points: 0 },
      { text: "balance", points: 0 },
    ],
    explanation: "Seeing things differently from a new height is a change in perspective, a more exact word than view.",
    definition: "The way things look from where you are, or how you think about them.",
    example: "From the airplane, my perspective made houses look like toys.",
    reviewNote: "Attitude and balance are both things that can change at the top of a slide, but neither explains the sandbox looking tiny. View is true and scores one, yet perspective covers how things look from where you stand. From that height is the evidence. All four are abstract nouns.",
  },
  {
    id: "fg-72", d: 9, prompt: "To make the paper boat, Finn followed the steps in exactly the right ___: fold, crease, flip, then pull.",
    options: [
      { text: "sequence", points: 2 },
      { text: "way", points: 1 },
      { text: "shape", points: 0 },
      { text: "rhythm", points: 0 },
    ],
    explanation: "Steps done one after another in the right order are a sequence.",
    definition: "The order that things happen in, one after another.",
    example: "Put the story pictures in sequence from first to last.",
    reviewNote: "Shape and rhythm are real words for paper folding, but the list fold, crease, flip, then pull is about which step comes next. Way scores one because it is loosely true, yet it does not name order. The list of steps with then is the evidence. All four are nouns.",
  },
  {
    id: "fg-73", d: 9, prompt: "When the family moved from sunny Florida to snowy Maine, it took Lucas a few months to ___ to the long, cold winters.",
    options: [
      { text: "adapt", points: 2 },
      { text: "react", points: 1 },
      { text: "travel", points: 0 },
      { text: "return", points: 0 },
    ],
    explanation: "Getting used to a new and different place over months is adapting, which is more than reacting.",
    definition: "Change the way you do things so you fit a new place.",
    example: "Polar bears adapt to the icy Arctic with thick fur.",
    reviewNote: "Travel and return are real verbs about moving, but Lucas already moved and has never lived in Maine, so he cannot return. React scores one because he does respond to the cold, yet it misses the slow change over months. A few months is the evidence. All four are base form verbs; the key is not the longest.",
  },
  {
    id: "fg-74", d: 9, prompt: "The coach clapped and repeated 'Keep your eyes on the ball!' three times to ___ how important it was.",
    options: [
      { text: "emphasize", points: 2 },
      { text: "explain", points: 1 },
      { text: "celebrate", points: 0 },
      { text: "question", points: 0 },
    ],
    explanation: "Saying something three times with claps to show it matters is emphasizing it.",
    definition: "Show that something is extra important, like by saying it louder or again.",
    example: "Mom tapped the sign to emphasize that we must walk.",
    reviewNote: "Celebrate fits the clapping and question is a real thing a coach does, but repeating one rule three times does neither. Explain scores one because the coach is telling the players something, yet repetition shows importance rather than adding meaning. Three times is the evidence. All four are base form verbs; the key ties for longest.",
  },
  {
    id: "fg-75", d: 9, prompt: "In just two sentences, Eva told the whole plot of the long movie, because she knew how to ___ a story.",
    options: [
      { text: "summarize", points: 2 },
      { text: "describe", points: 1 },
      { text: "memorize", points: 0 },
      { text: "criticize", points: 0 },
    ],
    explanation: "Telling a whole long story in two sentences is summarizing it, which is shorter than describing.",
    definition: "Tell the most important parts of something in just a few words.",
    example: "Can you summarize the book in one sentence?",
    reviewNote: "Memorize and criticize are real things you can do with a movie, but neither fits telling the whole plot in just two sentences. Describe scores one because she does tell about it, yet it misses the shortness. Just two sentences is the evidence. All four are verbs ending in the same sound band; the key ties for longest.",
  },
  {
    id: "fg-76", d: 10, prompt: "Before any video games, finishing homework is always Ben's top ___.",
    options: [
      { text: "priority", points: 2 },
      { text: "choice", points: 1 },
      { text: "hobby", points: 0 },
      { text: "favorite", points: 0 },
    ],
    explanation: "What you always do first because it matters most is your top priority.",
    definition: "The thing that matters most, so you do it first.",
    example: "Safety is the top priority at the pool.",
    reviewNote: "Hobby and favorite are words a child might try after top, but homework being done before games says it comes first, not that he loves it. Choice scores one because he does choose it, yet it misses that it always comes first. Before any video games is the evidence. All four are nouns; the key ties for longest.",
  },
  {
    id: "fg-77", d: 10, prompt: "The little tomato plant was flattened by the storm, but within a week it stood tall and grew new leaves, proving how ___ it was.",
    options: [
      { text: "resilient", points: 2 },
      { text: "healthy", points: 1 },
      { text: "tangled", points: 0 },
      { text: "hollow", points: 0 },
    ],
    explanation: "Bouncing back after being flattened shows the plant was resilient, which is more than healthy.",
    definition: "Able to bounce back and get strong again after something hard happens.",
    example: "The resilient team kept smiling after losing the game.",
    reviewNote: "Tangled and hollow are real ways a storm can leave a plant, but neither fits standing tall a week later. Healthy scores one because the plant is well again, yet resilient names the bouncing back. Flattened then standing tall is the evidence. All four are adjectives.",
  },
  {
    id: "fg-78", d: 10, prompt: "Thousands of fireflies blinking at the very same moment is a natural ___ that scientists travel far to study.",
    options: [
      { text: "phenomenon", points: 2 },
      { text: "event", points: 1 },
      { text: "habitat", points: 0 },
      { text: "resource", points: 0 },
    ],
    explanation: "A remarkable thing in nature that scientists come to study is a phenomenon, more exact than an event.",
    definition: "Something amazing in nature or the world that people notice and study.",
    example: "A rainbow is a phenomenon made by sunlight and rain.",
    reviewNote: "Habitat and resource are real science words about nature, but the blinking itself is not a place to live or something to use. Event scores one because it is something that happens, yet it misses how remarkable and study worthy it is. Scientists travelling to study it is the evidence. All four are nouns.",
  },
  {
    id: "fg-79", d: 10, prompt: "When Dad looked at the pouring rain and said, 'What lovely weather for a picnic,' he was being ___.",
    options: [
      { text: "sarcastic", points: 2 },
      { text: "funny", points: 1 },
      { text: "truthful", points: 0 },
      { text: "thoughtful", points: 0 },
    ],
    explanation: "Calling pouring rain lovely picnic weather means the opposite of the words, which is sarcastic.",
    definition: "Saying the opposite of what you mean, as a joke or to tease.",
    example: "'Great, more chores,' he said in a sarcastic voice.",
    reviewNote: "Truthful and thoughtful are real words for what a parent says, but lovely weather in pouring rain is not true, and nothing is being planned kindly. Funny scores one because it is a joke, yet sarcastic names saying the opposite. Pouring rain against lovely is the evidence. All four are adjectives; the key is not the longest.",
  },
  {
    id: "fg-80", d: 10, prompt: "After losing the chess game, Mira sat quietly to ___ on which moves had cost her the game so she could do better next time.",
    options: [
      { text: "reflect", points: 2 },
      { text: "think", points: 1 },
      { text: "complain", points: 0 },
      { text: "gossip", points: 0 },
    ],
    explanation: "Thinking back carefully about what happened so you can do better is reflecting.",
    definition: "Think carefully and quietly about something that already happened.",
    example: "At bedtime, I like to reflect on my day.",
    reviewNote: "Complain and gossip are real things a child might do after losing, but neither fits sitting quietly to work out which moves cost her the game. Think scores one because she is thinking, yet reflect names looking back to learn. Sitting quietly so she could do better is the evidence. All four are base form verbs; the key is not the longest.",
  },
];
