// Pure "what was this question, and what did she answer?" resolver for the
// parent dashboard (Jalal, 2026-08-29: "in this i actually want to see all
// the questions. in details if and when i want. also what choices there
// were, what she answered. the whole thing").
//
// A recorded ItemRecord stores only (genre, seed, d, response, bankId,
// points) — never the rendered question — so the full text has to be
// regenerated by replaying the genre's own deterministic generator. That is
// the same trick lib/engine/insights.ts's resolveHerPick and
// lib/engine/quality.ts already use, widened here from "her wrong pick" to
// the whole item: prompt, every option, which one she took, which one was
// best, and the explanation.
//
// DECISION #14 GOVERNS THIS FILE: a false detail is worse than no detail.
// Every path below returns null rather than render anything it cannot prove
// matches what she actually saw. The three ways a regeneration can lie:
//
//   1. Re-banded ramp. `remapSession` (scale.ts) rewrites item.d for
//      sessions recorded before a genre's cutover, so replaying that
//      genre's generator at the REMAPPED d yields a different item than she
//      saw. Guarded by `regenerable()` — a genre with any cutover after the
//      session date resolves to null, full stop.
//   2. Bank drift. An authored bank can gain/lose/reorder items between the
//      day she played and today, so the same (seed, d) can land on a
//      different entry. Guarded by requiring the regenerated bankId to equal
//      the recorded one.
//   3. Option-shuffle drift. Options are shuffled per-seed; if the shuffle
//      changed, her recorded index points at the wrong text. Guarded by
//      requiring the option at her index to score exactly the points she was
//      awarded.
//
// There is also a replay INPUT that is easy to get wrong: a block never
// repeats a bank entry, so app/play/page.tsx feeds `generate` the bankIds
// already used earlier in that same block (`usedBankIdsRef`, reset per
// block). That exclusion list steers both which entry is picked AND the
// per-seed option shuffle, so a faithful replay has to pass the same list —
// hence `RecordedItem.priorBankIds`. Omitting it does not produce a wrong
// answer, only a needlessly blank one: the replay lands on a different bank
// entry and guard 2 rejects it.
//
// Guard 3 cannot run when there is no response to check (a timeout, or a
// "Not fun" bail). Those still render the QUESTION — guards 1+2 prove the
// item is the right one — but `herAnswer` stays null, since the whole claim
// being made is "she gave no answer".
//
// NO answer and an UNREADABLE answer are different, and only the first is
// safe to render: a null/undefined response means she genuinely gave nothing
// (timeout, bail), while a response of the wrong shape means the record and
// this code disagree about what an answer even looks like — which is exactly
// the situation where "she gave no answer" would be a lie. `noAnswer()` draws
// that line, and every resolver below returns null on the second case.
import type { Difficulty, GenreId } from "./types";
import { GENRES } from "../genres";
import { SCALE_CHANGES } from "./scale";
import type { Token, SwapShopItem } from "../genres/swapShop";
import type { WhichTwoItem, WhichTwoResponse } from "../genres/whichTwo";
import type { ArithmeticItem } from "../genres/bankGenre";

export interface ViewOption {
  text: string;
  /** Per-option score where the genre awards partial credit (2/1/0 verbal); undefined when it is a plain right/wrong pick. */
  points?: number;
  /** She chose this option. */
  chosen: boolean;
  /** The best available answer (top-scoring option, or the keyed-correct one). */
  best: boolean;
}

export interface ItemView {
  /** The question exactly as she read it. */
  prompt: string;
  emoji?: string;
  /** Supporting lines shown above the question (Swap Shop's trade rules); empty for most genres. */
  rules: string[];
  /** Every choice she was offered, in the order she saw them. Empty for typed-answer genres. */
  options: ViewOption[];
  /** What she gave, rendered for a reader. Null when she gave nothing (timeout / bail) or it could not be proven. */
  herAnswer: string | null;
  /** The best answer, rendered for a reader. */
  correctAnswer: string | null;
  /** The genre's own "why" line, when it authored one. */
  explanation: string | null;
}

/** What the item log recorded, for the consistency guards. */
export interface RecordedItem {
  seed: number;
  d: number;
  response: unknown;
  bankId?: string;
  points: number;
  /** Session start — checked against this genre's scale cutovers (guard 1). */
  date: string;
  /**
   * The bankIds of every item that came BEFORE this one in the same block,
   * in order — what play excluded when it generated this item. Empty for the
   * first item of a block and for practice replays (which exclude nothing).
   */
  priorBankIds?: string[];
}

/**
 * Guard 1: false when this genre's ramp was re-banded AFTER the session was
 * recorded, because insights.ts will have remapped the item's difficulty and
 * the generator would replay a different question at the new number.
 */
export function regenerable(genre: GenreId, date: string): boolean {
  return !SCALE_CHANGES.some((ch) => ch.genre === genre && date < ch.cutover);
}

/** True only when nothing was recorded — never for a response of an unexpected shape (see the header note). */
const noAnswer = (r: unknown): boolean => r === null || r === undefined;

const tokens = (t: Token[]): string => t.join(" ");

/** Renders one Swap Shop trade rule as "⭐ ⭐ → 🪙 🪙 🪙". */
function ruleLine(r: { give: Token[]; get: Token[] }): string {
  return `${tokens(r.give)} → ${tokens(r.get)}`;
}

/** Marks up a choice list: `chosen` at her index, `best` on every top-scoring entry. */
function markOptions(
  opts: { text: string; points?: number }[],
  chosenIdx: number | null,
  bestIdx: number | null,
): ViewOption[] {
  const scored = opts.some((o) => typeof o.points === "number");
  const top = scored ? Math.max(...opts.map((o) => o.points ?? 0)) : null;
  return opts.map((o, i) => ({
    text: o.text,
    ...(typeof o.points === "number" ? { points: o.points } : {}),
    chosen: chosenIdx === i,
    best: top !== null ? (o.points ?? 0) === top : bestIdx === i,
  }));
}

/**
 * Rebuilds the full question an item recorded, or null when any guard fails.
 * Pure: same inputs always give the same result, no clock and no I/O.
 */
export function resolveItemView(genreId: GenreId, rec: RecordedItem): ItemView | null {
  if (!regenerable(genreId, rec.date)) return null;               // guard 1
  const genreDef = GENRES[genreId];
  if (!genreDef) return null;
  const d = rec.d as Difficulty;
  if (!Number.isInteger(d) || d < 1) return null;

  // Replay exactly what play did, exclusion list included (see header note).
  const opts = { excludeBankIds: rec.priorBankIds ?? [] };
  try {
    if (genreId === "whichTwo") return viewWhichTwo(genreDef.generate(rec.seed, d, opts) as WhichTwoItem, rec);
    if (genreId === "arithmetic") return viewArithmetic(genreDef.generate(rec.seed, d, opts) as ArithmeticItem, rec);
    if (genreId === "swapShop") return viewSwapShop(genreDef.generate(rec.seed, d, opts) as SwapShopItem, rec);
    return viewChoice(genreId, genreDef.generate(rec.seed, d, opts) as ChoiceShape, rec);
  } catch {
    return null;
  }
}

interface ChoiceShape {
  bankId?: string;
  prompt?: string;
  emoji?: string;
  options?: { text: string; points?: number }[];
  explanation?: string;
}

/**
 * The three verbal choice cousins still in play (Fill the Gap, Do You Know,
 * What Would You Do?) plus the retired Level 1/2 banks, which all share
 * bankGenre.ts's {prompt, options[], explanation} shape. A genre whose
 * generated item does not carry a prompt AND an options array is not a
 * choice item at all (the visual cousins) and resolves to null — those are
 * pictures, and there is no honest text rendering of them.
 */
function viewChoice(genreId: GenreId, item: ChoiceShape, rec: RecordedItem): ItemView | null {
  if (typeof item.prompt !== "string" || !Array.isArray(item.options)) return null;
  if (rec.bankId && item.bankId !== rec.bankId) return null;      // guard 2

  let chosen: number | null = null;
  if (!noAnswer(rec.response)) {
    if (typeof rec.response !== "number") return null;
    if (rec.response < 0 || rec.response >= item.options.length) return null;
    const opt = item.options[rec.response];
    if (typeof opt.points === "number" && opt.points !== rec.points) return null;  // guard 3
    chosen = rec.response;
  }

  const options = markOptions(item.options, chosen, null);
  return {
    prompt: item.prompt,
    ...(item.emoji ? { emoji: item.emoji } : {}),
    rules: [],
    options,
    herAnswer: chosen === null ? null : options[chosen].text,
    correctAnswer: options.find((o) => o.best)?.text ?? null,
    explanation: item.explanation ?? null,
  };
}

/**
 * Which Two Belong shows four things and asks for a PAIR plus the reason
 * that joins them, so "her answer" is two picks, not one. The pair carries
 * no score of its own — the reason does — so guard 3 is applied to the
 * reason index, and a response missing either half resolves to null.
 */
function viewWhichTwo(item: WhichTwoItem, rec: RecordedItem): ItemView | null {
  if (rec.bankId && item.bankId !== rec.bankId) return null;      // guard 2

  let herAnswer: string | null = null;
  let chosenReason: number | null = null;

  if (!noAnswer(rec.response)) {
    const r = rec.response as WhichTwoResponse;
    if (!r || !Array.isArray(r.pair) || r.pair.length !== 2 || typeof r.reason !== "number") return null;
    const [a, b] = [...r.pair].sort((x, y) => x - y);
    if (!Number.isInteger(a) || !Number.isInteger(b) || a === b) return null;
    if (a < 0 || b >= item.items.length) return null;
    if (r.reason < 0 || r.reason >= item.reasons.length) return null;
    const reason = item.reasons[r.reason];
    if (typeof reason.points === "number" && reason.points !== rec.points) return null;  // guard 3
    chosenReason = r.reason;
    herAnswer = `${item.items[a].text} + ${item.items[b].text} — “${reason.text}”`;
  }

  const [p, q] = item.pair;
  const options = markOptions(item.reasons, chosenReason, null);
  return {
    prompt: `Which two belong together? ${item.items.map((o) => o.text).join(" · ")}`,
    rules: [],
    options,
    herAnswer,
    correctAnswer: `${item.items[p].text} + ${item.items[q].text} — “${options.find((o) => o.best)?.text ?? ""}”`,
    explanation: item.explanation,
  };
}

/**
 * Story Sums is typed-answer, not multiple choice: there are no options, and
 * her response is the number she keyed in. Its bank entries are templates
 * filled from the same seeded rng, so the rendered text and answer both come
 * back exactly as she saw them once guard 2 confirms the same template.
 */
function viewArithmetic(item: ArithmeticItem, rec: RecordedItem): ItemView | null {
  if (rec.bankId && item.bankId !== rec.bankId) return null;      // guard 2
  if (!noAnswer(rec.response) && typeof rec.response !== "number") return null;
  const typed = typeof rec.response === "number" ? rec.response : null;
  // Guard 3, typed-answer form: a right answer must equal the key, a wrong
  // one must not — otherwise the replayed template drew different numbers.
  if (typed !== null && (typed === item.answer) !== (rec.points > 0)) return null;
  return {
    prompt: item.text,
    rules: [],
    options: [],
    herAnswer: typed === null ? null : String(typed),
    correctAnswer: String(item.answer),
    explanation: item.explanation,
  };
}

/**
 * Swap Shop is emoji piles, which DO render honestly as text: the trade
 * rules become "⭐ ⭐ → 🪙 🪙 🪙" lines and each option is its own pile. It
 * carries no bankId (it is generated, not authored), so guard 2 cannot run —
 * guard 1 is doing the real work here, and it is the reason her pre-2026-08-26
 * Swap Shop items deliberately show nothing.
 */
function viewSwapShop(item: SwapShopItem, rec: RecordedItem): ItemView | null {
  if (!Array.isArray(item.options) || item.options.length === 0) return null;
  let chosen: number | null = null;
  if (!noAnswer(rec.response)) {
    if (typeof rec.response !== "number") return null;
    if (rec.response < 0 || rec.response >= item.options.length) return null;
    // Guard 3, keyed form: her pick being the keyed answer must agree with
    // whether she scored.
    if ((rec.response === item.answer) !== (rec.points > 0)) return null;
    chosen = rec.response;
  }
  const options = markOptions(item.options.map((o) => ({ text: tokens(o) })), chosen, item.answer);
  return {
    prompt: `She has ${tokens(item.question)} — what is that worth?`,
    rules: item.rules.map(ruleLine),
    options,
    herAnswer: chosen === null ? null : options[chosen].text,
    correctAnswer: options[item.answer]?.text ?? null,
    explanation: null,
  };
}
